[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cyberdeus = "5P3yFKQ6yTHfLTD4GfcUXrbCk214cgwFfJ9N9fbPp4xb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/buysell.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./metaplex.so"